* Space
** keybindings
*** *
search word under cursor in buffer
*** /
search word under cursor
*** 0-9
jump to window
*** :
:
m-x
*** fs
save file
*** fm{
    change do block style
*** f
    R => rename current file
    ar => ranger!
    ft => tree!
    start + e => find replace in buffer?
    ? => find replace in project?
*** t
w => toggle invisible chars

*** p
b => buffers in project
*** x
**** w d
Google translate
** ranger
;+ => create directory
q  => quit

https://gist.github.com/adham90/0d85d023f9d4f1dd28ef

** custom
feg => open govwifi cheatsheet
fen => open notes
** Org Mode
use stars!
** Magit
*** g
**** l
     l => log
**** r
    refresh
**** s
     bb => checkout branch
     bc => Check out a new branch
     dr master => git diff master
     ds master => git diff master
     Fu => pull
**** M
     Git blame popup
**** h
     o View file in Github
** Shell
   '
** TODO
   Tab instead of %
   See last log message
   Git blame
   Current file path
   Git Blame inline?
   Don't leave magit buffers hanging around
   Intercative rename all instances
   Git pull
   Rename in Ranger, keep filename
   .DS_Store in terminal urg (ranger using something weird?)
   Renaming current file doesn't show current name.
   Disable rainbow parentheses for performance
   damn tmux copy
   damn tmux colours
   audio bell can get fucked
   Reload file? => DONE, Free
   Tabwidth in ruby? => DONE
   Get .spacemacs under version control => DONE
   Get spacemacs_notes.org under version control => DONE
   No syntax highlighting ranger => DONE
   How to rebase with magit => DONE

** DONE
   Macros
